version: "3.9"

services:
  # database service
  db:
    image: mariadb:10.5
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: smartsigi
      MYSQL_USER: smartsigiUser
      MYSQL_PASSWORD: smartsigiUserPassword
    volumes: 
      - ./db/smartsigi_db_init.sql:/docker-entrypoint-initdb.d/init.sql

  # adminer for db gui
  adminer: 
    image: adminer:latest 
    container_name: adminer
    environment:
      ADMINER_DEFAULT_SERVER: db
    restart: always
    ports:
      - 3307:8080
  # flask backend
  backend:
    container_name: flask_backend
    build: ./backend
    ports:
      - 5000:5000
    volumes:
      - ./backend:/app

  # frontend pwa
  #web:
  #  container_name: web_pwa
  #  build: ./web
 #   volumes:
#      - ./web:/app
#    ports:
#      - 3000:3000


